### ISSUE TITLE
Use s0pcm reader to measure current usage (in W) and total usage in KwH

### ISSUE THREAD

**Issue by wiljums** [darkrain-nl/home-assistant-addon-s0pcm-reader#5]
I want to use the addon to measure current usage in Watts and total usage in kWh. Do you know how to adapt the code to this?
The kWh-meter it is hooked up to is giving 1000 pulses per kWh.

**Comment by darkrain-nl** [comment]
Hi there,

Thanks for this request, I'm pretty sure we can get this to work fine ;-)

I think we just need to change the YAML to something like:
``` 
mqtt:
  sensor:
    - platform: mqtt
      state_topic: "s0pcmreader/1/total"
      name: "Total usage"
      unique_id: "total_usage"
      value_template: "{{ value_json | float / 1000 }}"
      unit_of_measurement: kWh
      state_class: total_increasing
    - platform: mqtt
      state_topic: "s0pcmreader/1/today"
      name: "current usage"
      unique_id: "current_usage"
      unit_of_measurement: W
```
